// demos/vue-tracker/src/views/ProjectForm.vue
<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useProjects } from '../stores/projects.js'

const router = useRouter()
const { addProject } = useProjects()

const title = ref('')
const description = ref('')
const status = ref('Planning')
const tagsInput = ref('')

const statusOptions = ['Active', 'In Progress', 'Planning', 'Complete']

function handleSubmit() {
  if (!title.value.trim()) return

  const tags = tagsInput.value
    .split(',')
    .map((t) => t.trim())
    .filter(Boolean)

  addProject({
    title: title.value.trim(),
    description: description.value.trim(),
    status: status.value,
    tags
  })

  router.push('/')
}
</script>

<template>
  <div class="form-page">
    <h2>Add New Project</h2>

    <form @submit.prevent="handleSubmit">
      <div class="form-group">
        <label for="title">Title</label>
        <input
          id="title"
          v-model="title"
          type="text"
          placeholder="Project name"
          required
        />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <textarea
          id="description"
          v-model="description"
          placeholder="What is this project about?"
        ></textarea>
      </div>

      <div class="form-group">
        <label for="status">Status</label>
        <select id="status" v-model="status">
          <option v-for="opt in statusOptions" :key="opt" :value="opt">
            {{ opt }}
          </option>
        </select>
      </div>

      <div class="form-group">
        <label for="tags">Tags</label>
        <input
          id="tags"
          v-model="tagsInput"
          type="text"
          placeholder="API, Charts, CSS"
        />
        <p class="form-hint">Separate tags with commas</p>
      </div>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary">Add Project</button>
        <router-link to="/" class="btn btn-secondary">Cancel</router-link>
      </div>
    </form>
  </div>
</template>

<style scoped>
/* Layout handled by global styles */
</style>

// demos/react-tracker/src/components/ProjectForm.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

function ProjectForm({ onAdd }) {
  const navigate = useNavigate()
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [status, setStatus] = useState('Planning')
  const [tagsInput, setTagsInput] = useState('')

  function handleSubmit(e) {
    e.preventDefault()

    if (!title.trim()) return

    const tags = tagsInput
      .split(',')
      .map(t => t.trim())
      .filter(t => t.length > 0)

    onAdd({ title: title.trim(), description: description.trim(), status, tags })
    navigate('/')
  }

  return (
    <div className="form-container">
      <h1>New Project</h1>
      <form onSubmit={handleSubmit} className="project-form">
        <div className="form-group">
          <label htmlFor="title">Title</label>
          <input
            id="title"
            type="text"
            value={title}
            onChange={e => setTitle(e.target.value)}
            placeholder="Project name"
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="description">Description</label>
          <textarea
            id="description"
            value={description}
            onChange={e => setDescription(e.target.value)}
            placeholder="What is this project about?"
            rows={4}
          />
        </div>

        <div className="form-group">
          <label htmlFor="status">Status</label>
          <select
            id="status"
            value={status}
            onChange={e => setStatus(e.target.value)}
          >
            <option value="Planning">Planning</option>
            <option value="Active">Active</option>
            <option value="In Progress">In Progress</option>
            <option value="Complete">Complete</option>
          </select>
        </div>

        <div className="form-group">
          <label htmlFor="tags">Tags (comma-separated)</label>
          <input
            id="tags"
            type="text"
            value={tagsInput}
            onChange={e => setTagsInput(e.target.value)}
            placeholder="React, API, CSS"
          />
        </div>

        <button type="submit" className="submit-btn">Add Project</button>
      </form>
    </div>
  )
}

export default ProjectForm
