// demos/vue-tracker/src/components/SearchBar.vue
<script setup>
defineProps({
  modelValue: {
    type: String,
    default: ''
  }
})

defineEmits(['update:modelValue'])
</script>

<template>
  <input
    type="text"
    class="search-input"
    placeholder="Search projects..."
    :value="modelValue"
    @input="$emit('update:modelValue', $event.target.value)"
  />
</template>

<style scoped>
/* Styles inherited from global .search-input */
</style>

// demos/react-tracker/src/components/SearchBar.jsx
function SearchBar({ value, onChange }) {
  return (
    <div className="search-bar">
      <input
        type="text"
        placeholder="Search projects..."
        value={value}
        onChange={e => onChange(e.target.value)}
        className="search-input"
      />
    </div>
  )
}

export default SearchBar
