// demos/react-tracker/src/components/ProjectList.jsx
import { useState } from 'react'
import ProjectCard from './ProjectCard'
import SearchBar from './SearchBar'

const STATUS_OPTIONS = ['All', 'Active', 'In Progress', 'Complete', 'Planning']

function ProjectList({ projects }) {
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState('All')

  const filtered = projects.filter(project => {
    const matchesSearch = project.title.toLowerCase().includes(search.toLowerCase())
    const matchesStatus = statusFilter === 'All' || project.status === statusFilter
    return matchesSearch && matchesStatus
  })

  return (
    <div className="project-list">
      <div className="list-header">
        <h1>Projects</h1>
        <p className="project-count">{filtered.length} project{filtered.length !== 1 ? 's' : ''}</p>
      </div>

      <SearchBar value={search} onChange={setSearch} />

      <div className="status-filters">
        {STATUS_OPTIONS.map(status => (
          <button
            key={status}
            className={`status-pill ${statusFilter === status ? 'active' : ''}`}
            onClick={() => setStatusFilter(status)}
          >
            {status}
          </button>
        ))}
      </div>

      <div className="cards-grid">
        {filtered.length > 0 ? (
          filtered.map(project => (
            <ProjectCard key={project.id} project={project} />
          ))
        ) : (
          <p className="empty-state">No projects match your filters.</p>
        )}
      </div>
    </div>
  )
}

export default ProjectList

// demos/vue-tracker/src/views/ProjectList.vue
<script setup>
import { ref, computed } from 'vue'
import { useProjects } from '../stores/projects.js'
import SearchBar from '../components/SearchBar.vue'
import ProjectCard from '../components/ProjectCard.vue'

const { projects } = useProjects()
const searchQuery = ref('')
const activeFilter = ref('All')

const statuses = ['All', 'Active', 'In Progress', 'Complete', 'Planning']

const filteredProjects = computed(() => {
  return projects.value.filter((project) => {
    const matchesSearch = project.title
      .toLowerCase()
      .includes(searchQuery.value.toLowerCase())
    const matchesStatus =
      activeFilter.value === 'All' || project.status === activeFilter.value
    return matchesSearch && matchesStatus
  })
})
</script>

<template>
  <div>
    <div class="filter-bar">
      <SearchBar v-model="searchQuery" />
      <div class="status-filters">
        <button
          v-for="status in statuses"
          :key="status"
          class="filter-pill"
          :class="{ active: activeFilter === status }"
          @click="activeFilter = status"
        >
          {{ status }}
        </button>
      </div>
    </div>

    <div v-if="filteredProjects.length" class="project-grid">
      <ProjectCard
        v-for="project in filteredProjects"
        :key="project.id"
        :project="project"
      />
    </div>

    <div v-else class="empty-state">
      <p>No projects found.</p>
      <p>Try adjusting your search or filter.</p>
    </div>
  </div>
</template>

<style scoped>
/* Layout handled by global styles */
</style>
